"""
Generate SAT Math figure images and save to public/ for the app.
Run from project root: python scripts/generate_math_images.py
"""
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import os

OUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'public')
os.makedirs(OUT_DIR, exist_ok=True)

print("Generating SAT Math images in", OUT_DIR)

# Image 1: Triangle with angles 45, 65, and x (m1-4)
plt.figure(figsize=(5, 4))
pts = np.array([[0, 0], [4, 0], [1.5, 3]])
polygon = plt.Polygon(pts, fill=False, edgecolor='black', linewidth=2)
plt.gca().add_patch(polygon)
plt.text(0.3, 0.2, '45°', fontsize=12)
plt.text(3.2, 0.2, '65°', fontsize=12)
plt.text(1.4, 2.3, 'x°', fontsize=12)
plt.xlim(-0.5, 4.5)
plt.ylim(-0.5, 3.5)
plt.axis('off')
plt.savefig(os.path.join(OUT_DIR, 'm1_4_triangle.png'), dpi=150, bbox_inches='tight')
plt.close()

# Image 2: Parallel lines with transversal (m1-15)
plt.figure(figsize=(5, 4))
plt.plot([-1, 5], [2, 2], color='black', linewidth=2)
plt.plot([-1, 5], [0, 0], color='black', linewidth=2)
plt.plot([0, 4], [-1, 3], color='blue', linewidth=2)
plt.text(2.5, 2.2, '110°', fontsize=12, fontweight='bold')
plt.text(1.2, 0.2, 'y°', fontsize=12, fontweight='bold')
plt.xlim(-1, 5)
plt.ylim(-1, 3)
plt.axis('off')
plt.savefig(os.path.join(OUT_DIR, 'm1_15_parallel.png'), dpi=150, bbox_inches='tight')
plt.close()

# Image 3: Scatterplot with line of best fit (m1-19)
plt.figure(figsize=(5, 4))
np.random.seed(42)
x_data = np.random.uniform(1, 8, 20)
y_data = 10 * x_data + 30 + np.random.normal(0, 5, 20)
plt.scatter(x_data, y_data, color='black', alpha=0.6)
plt.plot([1, 8], [40, 110], color='blue', linewidth=2, linestyle='--')
plt.xlabel("Hours Studied")
plt.ylabel("Test Score")
plt.title("Study Hours vs. Test Score")
plt.grid(True, linestyle='--', alpha=0.5)
plt.savefig(os.path.join(OUT_DIR, 'm1_19_scatterplot.png'), dpi=150, bbox_inches='tight')
plt.close()

# Image 4: Circle in xy-plane (m2-2)
fig, ax = plt.subplots(figsize=(5, 5))
circle2 = plt.Circle((3, -2), 3, color='blue', fill=False, linewidth=2)
ax.add_patch(circle2)
plt.plot(3, -2, 'ko')
plt.plot(3, 1, 'ro')
plt.text(3.2, -2.2, 'Center (3, -2)', fontsize=10)
plt.text(3.2, 1, '(3, 1)', fontsize=10)
plt.axhline(0, color='black', linewidth=1)
plt.axvline(0, color='black', linewidth=1)
plt.grid(True, linestyle='--', alpha=0.5)
ax.set_xlim(-1, 7)
ax.set_ylim(-6, 2)
ax.set_aspect('equal')
plt.title("Circle in xy-plane")
plt.savefig(os.path.join(OUT_DIR, 'm2_2_circle_graph.png'), dpi=150, bbox_inches='tight')
plt.close()

# Image 5: Right triangle 6-8-10 (m2-4)
plt.figure(figsize=(5, 4))
pts_rt = np.array([[0, 0], [8, 0], [0, 6]])
poly_rt = plt.Polygon(pts_rt, fill=False, edgecolor='black', linewidth=2)
plt.gca().add_patch(poly_rt)
plt.plot([0, 0.5, 0.5], [0.5, 0.5, 0], color='black', linewidth=1)
plt.text(-0.3, -0.3, 'C', fontsize=14, fontweight='bold')
plt.text(8.2, -0.3, 'A', fontsize=14, fontweight='bold')
plt.text(-0.3, 6.2, 'B', fontsize=14, fontweight='bold')
plt.text(4, 3.5, '10', fontsize=12, fontweight='bold')
plt.xlim(-1, 9)
plt.ylim(-1, 7)
plt.axis('off')
plt.savefig(os.path.join(OUT_DIR, 'm2_4_right_triangle.png'), dpi=150, bbox_inches='tight')
plt.close()

print("Done. Images saved in", OUT_DIR)
